ringmaster/config/routes.rb
Rails.application.routes.draw do

  root 'venues#index'

  resources :venues do
       resource :events
end

  resources :events do
      resource :bands
end

  resources :bands

end

ringmaster/app/models/band.rb
class Band < ActiveRecord::Base
has_many :events


end

ringmaster/app/models/event.rb
class Event < ActiveRecord::Base
belongs_to :band
belongs_to :venue

def self.search(search)
  if search
    find_by(:all, :conditions => ['date LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

end

ringmaster/app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :events
  has_many :bands, :through => :event
end

ringmaster/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ringmaster/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :find_band, only: [:show, :edit, :update, :destroy]

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.create(band_params)
    redirect_to @band
  end

  def show
  end

  def edit
  end

  def update
    @band.update(band_params)
    redirect_to @band
  end

  def destroy
    @band.destroy
    redirect_to bands_path
  end

  private

  def find_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name, :genre, :kid_friendly, :video_url)
  end
end

ringmaster/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show, :edit, :update, :destroy, :create]

  def index
    @events = Event.all
    if params[:search]
    Event.all(:conditions => { :date => Date.strptime(date, '%d-%m-%Y') })
  end
end



  def new
    @event = Event.new
  end

def create
    @event = Event.create(event_params)

  end

  def search
  @event = Event.search params[:search]
   redirect_to @event
end

  def show

  end


  def edit
  end

  def update
    @event.update(event_params)
    redirect_to @event
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:date, :start_time, :venue_id, :band_id, :kid_friendly)
  end
end

ringmaster/app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :find_hero, only: [:show, :edit, :update, :destroy]

  def index
    @heros = Hero.all
  end

  def new
    @hero = Hero.new
  end

  def create
    @hero = Hero.create(hero_params)
    redirect_to @hero
  end

  def show
  end

  def edit
  end

  def update
    @hero.update(hero_params)
    redirect_to @hero
  end

  def destroy
    @hero.destroy
    redirect_to heros_path
  end

  private

  def find_hero
    @hero = Hero.find(params[:id])
  end

  def hero_params
    params.require(:hero).permit(:name, :secret_identity, :image_url)
  end
end

ringmaster/app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :find_venue, only: [:show, :edit, :update, :destroy]


  def index
    @venues = Venue.all

  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.create(venue_params)
    redirect_to @venue
  end

  def show
  end

  def edit
  end

  def update
    @venue.update(venue_params)
    redirect_to @venue
  end

  def destroy
    @venue.destroy
    redirect_to venues_path
  end

  private

  def find_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :city, :state, :kid_friendly)
  end
end

ringmaster/app/helpers/application_helper.rb
module ApplicationHelper
end

ringmaster/app/views/bands/_manage_form.html.erb
<%= form_for @band do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.label :video_url %>
  <%= f.text_field :video_url %>

  <%= f.label :kid_friendly %>
  <%= f.check_box :kid_friendly %>

  <%= f.submit "Submit" %>
<% end %>

ringmaster/app/views/bands/edit.html.erb
<h1>Edit <%= @hero.name %></h1>

<%= render "manage_form" %>

<hr>

<%= form_for @hero, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<p><%= link_to "Cancel", @hero %></p>

ringmaster/app/views/bands/index.html.erb
<h1>RingMaster</h1>
<hr>

----------- LIST OF VENUES ---------<br>
<% @venues.each do |venue| %>
  <%= link_to venue.name, venue %>
<% end %>
------------------------------------<br>

<%= link_to "Add A New Venue", new_venue_path %>

<%= link_to "Add A New Band", new_band_path %>

Search all events by date button here





  <!--List All Venues
  <!--Create Venue
  <!--Create Band
  <!--Search All Events By Date

ringmaster/app/views/bands/new.html.erb
<h1>Add A Band</h1>

<%= render "manage_form" %>

<p><%= link_to "Cancel", bands_path %>

ringmaster/app/views/bands/show.html.erb
Band Information:<br>
<hr>

<p>Band Name: <h1><%= @band.name %></h1></p><br>
<p>Genre: <h1><%= @band.genre %> </h1>
<p>Video : <iframe width="420" height="315" src="//<%= @band.video_url %>" frameborder="0" allowfullscreen></iframe></p><br>
<p>Kid Friendly?: <h1><%= @band.kid_friendly %></h1></p><br>

<hr>
<p><%= link_to "Edit Band", edit_band_path(@band) %></p>
<p><%= link_to "All Bands", bands_path %></p>

ringmaster/app/views/events/_manage_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :start_time %>
  <%= f.time_field :start_time %>


  <%= f.label :band_id %>
  <%= f.collection_select :band_id, Band.all, :name, :name %>



  <%= f.submit "Submit" %>
<% end %>

ringmaster/app/views/events/delete.html.erb
<form action="/<%= @event.id %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input name="authenticity_token" type="hidden" value="<% form_authenticity_token %>">

  <button>Delete This Event</button>
</form>

ringmaster/app/views/events/edit.html.erb
<h1>Edit <%= @event.name %></h1>

<%= render "manage_form" %>

<hr>

<%= form_for @event, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<p><%= link_to "Cancel", @event %></p>

ringmaster/app/views/events/index.html.erb
----------- LIST OF EVENTS ---------<br>
<% @events.each do |event| %>
  <%= link_to event.date, event %>
<% end %>
------------------------------------<br>

<%= link_to "Add A New Event", new_venue_path %>

ringmaster/app/views/events/new.html.erb
<h1>Add An Event</h1>

<%= render "manage_form" %>

<p><%= link_to "Cancel", events_path %>

ringmaster/app/views/events/show.html.erb
<h1>Event Information...</h1><br>
<hr>

<p>Event Date: <h1><%= @event.date %></p><br>
<p>Start Time: <h1><%= @event.start_time %></p><br>

<p>Venue: <h1><%= @event.venue_id %></p><br>
<p>Band: <h1><%= @event.band_id %></p><br>

<hr>
<p><%= link_to "Edit Event", edit_event_path(@event) %></p>
delete event button here
<p><%= link_to "Return to All Venues", venues_path %></p>

ringmaster/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ring-Master! - Your venue and show manager</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="page">
    <center>
    <%= image_tag "brand/logo.png", alt: "" %><br>
    <%= yield %>
  </div>

</body>
</html>

ringmaster/app/views/venues/_manage_form.html.erb
<%= form_for @venue do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :kid_friendly %>
  <%= f.check_box :kid_friendly %>

  <%= f.submit "Submit" %>
<% end %>

ringmaster/app/views/venues/_search_form.html.erb
<%= form_tag :controller => 'events', :action => 'search', :method => 'get' do %>
2      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
3      <%= submit_tag "Search", :name => nil %>
4      <%= link_to_function "Clear", "$('search_field').clear()" %>
5  <% end %>

ringmaster/app/views/venues/delete.html.erb
<form action="/<%= @venue.id %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input name="authenticity_token" type="hidden" value="<% form_authenticity_token %>">

  <button>Delete This Venue</button>
</form>

ringmaster/app/views/venues/edit.html.erb
<h1>Edit <%= @hero.name %></h1>

<%= render "manage_form" %>

<hr>

<%= form_for @hero, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<p><%= link_to "Cancel", @hero %></p>

ringmaster/app/views/venues/index.html.erb
<h1>RingMaster</h1>
<hr>

<hr><br>
----------- LIST OF VENUES ---------<br>
<% @venues.each do |venue| %>
  <li><%= link_to venue.name, venue %></li><br>
<% end %>
------------------------------------<br>

<%= link_to "Add A New Venue...", new_venue_path %><!-- should get venue form -->
button doing the same thing:

<%= button_to "Add a New Venue", new_venue_path, :class => "button", :method => :get  %>

<%= link_to "Add A New Band...", new_band_path %><!-- should get band form -->
button doing the same thing:

<%= button_to "Add a New Band", new_band_path, :class => "button", :method => :get  %>
(turns out buttons are POST by default!)

<hr>

<h1>Search for an Event by Date:</h1><br>

<%= form_tag events_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<br>
<hr>

ringmaster/app/views/venues/new.html.erb
<h1>Add a Venue</h1>

<%= render "manage_form" %>

<p><%= link_to "Cancel", venues_path %>

ringmaster/app/views/venues/show.html.erb
<h1>Venue Details...</h1><br>
<hr>

<p>Venue Name: <h1><%= @venue.name %></h1></p><br>
<p>Location: <h1><%= @venue.city %>, <%= @venue.state %></h1></p><br>
<p>Kid Friendly: <h1><%= @venue.kid_friendly %></h1></p><br>

<hr>

<p><%= link_to "Create An Event", new_event_path(@event) %></p>
<p><%= link_to "Delete this Venue", venue_path %></p>
<p><%= link_to "All Venues", venues_path %></p>